#!/bin/bash
# install.sh — SAMBA full installer
# Run once from the project directory:  bash install.sh
#
# What it does:
#   1. Checks Python version (3.8+ required)
#   2. Installs all required Python packages
#   3. Generates a launch script with the correct Python and project path
#   4. Creates a GNOME desktop entry (taskbar / application menu)
#   5. Sets up the config directory (~/.config/moke_scan)

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Resolve real user (handles both  sudo bash install.sh  and  bash install.sh) ──
if [ -n "$SUDO_USER" ]; then
    REAL_USER="$SUDO_USER"
    REAL_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
else
    REAL_USER="$(whoami)"
    REAL_HOME="$HOME"
fi

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BOLD='\033[1m'; NC='\033[0m'
ok()  { echo -e "  ${GREEN}✓${NC} $1"; }
warn(){ echo -e "  ${YELLOW}⚠${NC} $1"; }
err() { echo -e "  ${RED}✗${NC} $1"; }
hdr() { echo -e "\n${BOLD}$1${NC}"; }

echo -e "${BOLD}"
echo "  ╔══════════════════════════════════╗"
echo "  ║       SAMBA Installer            ║"
echo "  ║  ETH Zürich — Intermag Lab       ║"
echo "  ╚══════════════════════════════════╝"
echo -e "${NC}"
echo "  Project directory: $SCRIPT_DIR"

# ── Detect Python ─────────────────────────────────────────────────────────────
hdr "[ 1 / 5 ]  Python"

# Prefer the Python that called this script; fall back to python3
PYTHON="${PYTHON:-$(command -v python3 2>/dev/null || command -v python)}"
if [ -z "$PYTHON" ]; then
    err "No Python found. Install Python 3.8+ or set PYTHON=/path/to/python."
    exit 1
fi

PY_VER=$("$PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$("$PYTHON" -c "import sys; print(sys.version_info.major)")
PY_MINOR=$("$PYTHON" -c "import sys; print(sys.version_info.minor)")
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 8 ]; }; then
    err "Python 3.8+ required — found $PY_VER at $PYTHON"
    exit 1
fi

PYTHON_PATH=$("$PYTHON" -c "import sys; print(sys.executable)")
ok "Python $PY_VER  →  $PYTHON_PATH"

# Warn if running as root without an explicit environment
if [ "$(id -u)" -eq 0 ] && [ -z "$CONDA_DEFAULT_ENV" ] && [ -z "$VIRTUAL_ENV" ]; then
    warn "Running as root with the system Python — this is not recommended."
    warn "Packages installed here may conflict with the OS or not be user-visible."
    warn "Preferred: run  bash install.sh <conda_env>  as a normal user."
fi

# Warn if running outside a conda / venv environment
if [ -z "$CONDA_DEFAULT_ENV" ] && [ -z "$VIRTUAL_ENV" ]; then
    warn "No active conda or venv environment detected — installing to system Python."
    warn "Consider activating your environment first."
fi

# ── Python packages ───────────────────────────────────────────────────────────
hdr "[ 2 / 5 ]  Python packages"

# Bootstrap pip if missing (common on bare Debian/Ubuntu system Python)
if ! "$PYTHON" -m pip --version &>/dev/null; then
    warn "pip not found — attempting to install it…"
    if command -v apt-get &>/dev/null; then
        apt-get install -y python3-pip &>/dev/null \
            && ok "pip installed via apt-get" \
            || warn "apt-get install python3-pip failed — try manually: sudo apt-get install python3-pip"
    else
        "$PYTHON" -m ensurepip --upgrade &>/dev/null \
            && ok "pip bootstrapped via ensurepip" \
            || warn "Could not install pip — install manually then re-run install.sh"
    fi
fi

# Format: "pip_package_name:import_name"
PACKAGES=(
    "PyQt6:PyQt6"
    "numpy:numpy"
    "matplotlib:matplotlib"
    "h5py:h5py"
    "pytango:tango"
)

FAILED=()
for entry in "${PACKAGES[@]}"; do
    pip_name="${entry%%:*}"
    import_name="${entry##*:}"
    if "$PYTHON" -c "import $import_name" 2>/dev/null; then
        ver=$("$PYTHON" -c "import $import_name; print(getattr($import_name, '__version__', '?'))" 2>/dev/null || echo "?")
        ok "$pip_name  ($ver)"
    else
        echo "    Installing $pip_name ..."
        if "$PYTHON" -m pip install "$pip_name" -q; then
            ok "$pip_name  installed"
        else
            warn "$pip_name  install FAILED — you may need to install it manually"
            FAILED+=("$pip_name")
        fi
    fi
done

if [ ${#FAILED[@]} -gt 0 ]; then
    echo ""
    warn "The following packages could not be installed automatically:"
    for pkg in "${FAILED[@]}"; do
        echo "      pip install $pkg"
    done
    if [[ " ${FAILED[*]} " == *" pytango "* ]]; then
        warn "pytango sometimes requires a conda install instead:"
        echo "      conda install -c tango-controls pytango"
    fi
fi

# ── Launch script ─────────────────────────────────────────────────────────────
hdr "[ 3 / 5 ]  Launch script"

LAUNCH="$SCRIPT_DIR/launch_samba.sh"
cat > "$LAUNCH" << LAUNCH_EOF
#!/bin/bash
# Auto-generated by install.sh — re-run install.sh to regenerate
cd "$SCRIPT_DIR"
exec "$PYTHON_PATH" "$SCRIPT_DIR/samba.py"
LAUNCH_EOF
chmod +x "$LAUNCH"
ok "launch_samba.sh  →  $LAUNCH"

# ── Desktop entry ─────────────────────────────────────────────────────────────
hdr "[ 4 / 5 ]  Desktop entry"

ICON_SRC="$SCRIPT_DIR/samba_icon_256.png"
ICON_DEST="$REAL_HOME/.local/share/icons/hicolor/256x256/apps/samba.png"
APPS_DIR="$REAL_HOME/.local/share/applications"
ICONS_DIR="$REAL_HOME/.local/share/icons/hicolor/256x256/apps"

mkdir -p "$APPS_DIR"
mkdir -p "$ICONS_DIR"

cat > "$APPS_DIR/samba.desktop" << DESK_EOF
[Desktop Entry]
Name=SAMBA
Comment=SAMBA — ETH Zürich Intermag Lab
Exec=$LAUNCH
Icon=$ICON_DEST
Terminal=false
Type=Application
Categories=Science;Education;
StartupWMClass=samba
DESK_EOF

if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$ICON_DEST"
    gtk-update-icon-cache -f -t "$REAL_HOME/.local/share/icons/hicolor" 2>/dev/null || true
    ok "Icon installed"
else
    warn "samba_icon_256.png not found — desktop entry will have no icon"
fi

# Fix ownership so the real user owns their own files when run via sudo
if [ -n "$SUDO_USER" ]; then
    chown -R "$REAL_USER:" "$APPS_DIR/samba.desktop" "$ICON_DEST" 2>/dev/null || true
fi

update-desktop-database "$APPS_DIR" 2>/dev/null || true
ok "Desktop entry installed  →  $APPS_DIR/samba.desktop"

# ── Config directory ──────────────────────────────────────────────────────────
hdr "[ 5 / 5 ]  Config directory"

CONFIG_DIR="$REAL_HOME/.config/moke_scan"
mkdir -p "$CONFIG_DIR"
if [ -n "$SUDO_USER" ]; then
    chown "$REAL_USER:" "$CONFIG_DIR" 2>/dev/null || true
fi
ok "$CONFIG_DIR"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}  ══════════════════════════════════${NC}"
if [ ${#FAILED[@]} -eq 0 ]; then
    echo -e "${GREEN}${BOLD}  Installation complete!${NC}"
else
    echo -e "${YELLOW}${BOLD}  Installation complete (with warnings).${NC}"
fi
echo -e "${BOLD}  ══════════════════════════════════${NC}"
echo ""
echo "  Launch from terminal:"
echo "    bash $LAUNCH"
echo ""
echo "  Or find SAMBA in the application menu"
echo "  (log out and back in if it doesn't appear)."
echo ""
