#!/bin/bash
# launch_samba.sh — generated by install.sh
# Run install.sh first to set the correct Python path for your environment.
echo "Run  bash install.sh  first to configure this launch script."
exit 1
